version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=my_auth
      - POSTGRES_PASSWORD=my_auth
      - POSTGRES_DATABASE=my_auth
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning

volumes:
  db:
    driver: local
  redis:
    driver: local
